/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package azura.server.app;

import azura.server.list.LinkedList;
import org.apache.commons.text.WordUtils;

import static azura.server.app.MessageUtils.getMessage;
import static azura.server.utilities.StringUtils.join;
import static azura.server.utilities.StringUtils.split;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
